# Generated by Django 5.0.4 on 2024-04-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointed_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
